import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>WeGroup FE assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to your assignment!</h1>

        <p>
          Get started by reading the <code>README.md</code>
        </p>
        <p>You can remove the code of this file.</p>
      </main>
    </div>
  );
};

export default Home;
